name: my_web_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  parse_server_sdk_flutter: ^6.0.0 # Latest version for web support
  sembast: ^3.3.1 # A version that does not conflict
  idb_shim: ^2.4.0 # Newer version with fixed exports
  connectivity_plus: 3.0.6
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
